import * as fs from "node:fs";
import * as path from "node:path";
import type { TestCategory, TestSuggestion } from "./types";

const CATEGORY_ORDER: TestCategory[] = [
  "happy-path",
  "validation",
  "edge-case",
  "security",
  "ux",
  "accessibility",
];

const CATEGORY_LABELS: Record<TestCategory, string> = {
  "happy-path": "Happy Path",
  validation: "Validation",
  "edge-case": "Edge Cases",
  security: "Security",
  ux: "UX",
  accessibility: "Accessibility",
};

function slugFromUrl(url: string): string {
  try {
    const parsed = new URL(url);
    const pathname = parsed.pathname.replace(/^\/|\/$/g, "");
    if (!pathname) return "home";
    return pathname.replace(/\//g, "-");
  } catch {
    return "page";
  }
}

function classNameFromSlug(slug: string): string {
  return slug
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

export function generateSpec(
  url: string,
  pageTitle: string,
  suggestions: TestSuggestion[],
  outputOverride?: string,
): { content: string; outputPath: string } {
  const slug = slugFromUrl(url);
  const className = classNameFromSlug(slug);

  // Group by category
  const grouped = new Map<TestCategory, TestSuggestion[]>();
  for (const cat of CATEGORY_ORDER) {
    const items = suggestions.filter((s) => s.category === cat);
    if (items.length > 0) grouped.set(cat, items);
  }

  // Build spec content
  const lines: string[] = [];
  lines.push('import { test } from "../../src/fixtures";');
  lines.push("");
  lines.push(`// Test plan for: ${pageTitle || slug}`);
  lines.push(`// URL: ${url}`);
  lines.push(`// Generated by: othello analyze`);
  lines.push(`// Total: ${suggestions.length} tests`);
  lines.push("");

  for (const [category, items] of grouped) {
    const label = CATEGORY_LABELS[category];
    lines.push(`test.describe("${className} — ${label}", () => {`);
    lines.push(`  test.beforeEach(async ({ page }) => {`);
    lines.push(`    await page.goto("${url}");`);
    lines.push("  });");
    lines.push("");

    for (const item of items) {
      const isSkipped = item.priority === "medium" || item.priority === "low";
      if (isSkipped) {
        lines.push(`  // Remove .skip when ready`);
        lines.push(`  test.skip("${item.title}", async ({ page }) => {`);
      } else {
        lines.push(`  test("${item.title}", async ({ page }) => {`);
      }
      lines.push("    // TODO: implement");
      lines.push("  });");
      lines.push("");
    }

    lines.push("});");
    lines.push("");
  }

  const content = lines.join("\n");

  // Determine output path
  let outputPath: string;
  if (outputOverride) {
    outputPath = path.resolve(outputOverride);
  } else {
    const fileName = `${slug}.spec.ts`;
    const e2eDir = path.resolve("tests", "e2e");
    if (fs.existsSync(e2eDir)) {
      outputPath = path.join(e2eDir, fileName);
    } else {
      outputPath = path.resolve(fileName);
    }
  }

  return { content, outputPath };
}
